### ISSUE TITLE
Lightswitch first render issues

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#362]
### Current Behavior

On initial page load the icon in the switch doesn't render until after an interaction and it defaults into the Light mode even if the user system preference is set to Dark mode.

### Steps To Reproduce

Brave and Safari in private mode
Open Theme drop down menu

![image](https://user-images.githubusercontent.com/52020637/195675238-d10dd66b-1d48-4e5e-b861-1e053d908335.png)

**Comment by endigo9740** [comment]
There was two issues for this:

1. The theme colors were not being applied consistently because the state was not set properly for the defaults (system preference)
2. The LightSwitch store value was not being updated until interacted with, so by default when using the system preference, the value was undefined rather than a boolean.

Both have been fixed and will go live with the QA branch I've created.

**Comment by Zerdayne** [comment]
Something similar is still happening. I'm using this in a tauri application.

```ts
$: {
    console.log($storePrefersDarkScheme);
    console.log($storeLightSwitch);
}
```
will log true for both.

The visualization I get after starting: 
![image](https://user-images.githubusercontent.com/36093039/214858789-0b5789ee-5a80-4e18-8219-a19b5deff4e8.png)
with the light theme in the full application applied.

Clicking once the switch fixes the visualization of the switch (switch button is left, sun icon is showing). Clicking twice activates the dark theme. At this point the switch works perfectly fine.

**Comment by cappscolton** [comment]
> Something similar is still happening. I'm using this in a tauri application.
> 
> ```ts
> $: {
>     console.log($storePrefersDarkScheme);
>     console.log($storeLightSwitch);
> }
> ```
> 
> will log `true` for both.
> 
> The visualization I get after starting the application: ![image](https://user-images.githubusercontent.com/36093039/214858789-0b5789ee-5a80-4e18-8219-a19b5deff4e8.png) with the light theme in the full application applied.
> 
> Clicking once the switch fixes the visualization of the switch (switch button is left, sun icon is showing). Clicking twice activates the dark theme. At this point the switch works perfectly fine.

did you ever find a fix for this secondary issue? seems to still be around in tauri projects.

**Comment by endigo9740** [comment]
@cappscolton you might read through this PR and the related issue. Seems like this might fix this?
https://github.com/skeletonlabs/skeleton/pull/1440
